# Generated by Django 5.2.2 on 2025-06-06 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('38cc0f38-9dd8-40d0-9186-22d0af43d818'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID')),
                ('file', models.FileField(upload_to='uploaded_files/public/', verbose_name='File')),
                ('zipped_file_path', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Zip Path on Supabase')),
                ('lines_per_file', models.IntegerField(blank=True, null=True, verbose_name='Number of lines per file')),
                ('size_per_file', models.IntegerField(blank=True, null=True, verbose_name='Size Per File(Mb)')),
                ('bucket_name', models.CharField(default='chunkfiles', max_length=1024, verbose_name='Storage Bucket')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of split')),
            ],
        ),
    ]
