# Generated by Django 5.2.1 on 2025-05-30 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('553e441d-3b67-40a5-9503-9a22f6f28092'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID')),
                ('file', models.FileField(upload_to='uploaded_files/public/', verbose_name='File')),
            ],
        ),
    ]
