# Generated by Django 5.2.1 on 2025-06-01 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('781f5c53-0949-40b3-af1d-c7d362df8b15'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID'),
        ),
    ]
