# Generated by Django 5.2.1 on 2025-06-04 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitfile', '0002_alter_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lines_per_file',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of lines per file'),
        ),
        migrations.AddField(
            model_name='file',
            name='size_per_file',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size Per File(Mb)'),
        ),
        migrations.AddField(
            model_name='file',
            name='zipped_file_path',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Zip Path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('93144294-e8c2-4664-9728-887b28a9a227'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID'),
        ),
    ]
