# Generated by Django 5.2.2 on 2025-06-07 00:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitfile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('fa49cb98-3e10-4bd2-adc2-400da71b4f39'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID'),
        ),
    ]
