# Generated by Django 5.2.3 on 2025-06-11 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitfile', '0003_alter_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='operation',
            field=models.CharField(default=1, max_length=200, verbose_name='Operation done on file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('31cb4f55-ba83-4bd1-9f93-fa44a7432920'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID'),
        ),
    ]
