# Generated by Django 5.2.1 on 2025-06-04 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitfile', '0003_file_lines_per_file_file_size_per_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('dd1b4577-cc2f-42d2-aa94-70e6276f61bb'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='zipped_file_path',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Zip Path on Supabase'),
        ),
    ]
