# Generated by Django 5.2.1 on 2025-06-05 08:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitfile', '0004_alter_file_id_alter_file_zipped_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of split'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('9c57776a-bcec-450a-972d-92e61ec6f7fb'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID'),
        ),
    ]
