# Generated by Django 5.2.3 on 2025-06-13 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitfile', '0004_file_operation_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('e28667a6-12d8-4007-b85e-63d1973b7b7a'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID'),
        ),
    ]
