# Generated by Django 5.2.1 on 2025-06-06 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitfile', '0005_file_created_at_alter_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='bucket_name',
            field=models.CharField(default='chunkfiles', max_length=1024, verbose_name='Storage Bucket'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.UUID('818afe67-e8c1-4a93-bcf5-b1c377634585'), primary_key=True, serialize=False, unique=True, verbose_name='File UUID'),
        ),
    ]
